# Generated by Django 5.1.3 on 2025-02-16 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('surname', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('course', models.CharField(blank=True, choices=[('FS', 'FS'), ('QACX', 'QACX'), ('JCX', 'JCX'), ('JSCX', 'JSCX'), ('FE', 'FE'), ('PCX', 'PCX')], max_length=10, null=True)),
                ('course_format', models.CharField(blank=True, choices=[('static', 'static'), ('online', 'online')], max_length=15, null=True)),
                ('course_type', models.CharField(blank=True, choices=[('pro', 'pro'), ('minimal', 'minimal'), ('premium', 'premium'), ('incubator', 'incubator'), ('vip', 'vip')], max_length=100, null=True)),
                ('sum', models.IntegerField(blank=True, null=True)),
                ('already_paid', models.IntegerField(blank=True, db_column='alreadyPaid', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('utm', models.CharField(blank=True, max_length=100, null=True)),
                ('msg', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('In Work', 'In Work'), ('New', 'New'), ('Aggre', 'Aggre'), ('Disaggre', 'Disaggre'), ('Dubbing', 'Dubbing')], db_index=True, max_length=15, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='groups.group')),
                ('manager', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='orders.orders')),
            ],
        ),
    ]
